### ISSUE TITLE
[stacks-coordinator] Stacks transaction construction

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#14]
Add capabilities to the coordinator to construct the mint and burn sBTC stacks transactions. This is a part of the `FeeWallet` in the coordinator design, but it could be broken out to a separate `StacksWallet`.

```rust
pub trait FeeWallet {
    fn mint_sbtc(&self, op: &stacks_node::PegInOp) -> stacks_node::StacksTransaction;
    fn burn_sbtc(&self, op: &stacks_node::PegOutRequestOp) -> stacks_node::StacksTransaction;
    fn set_wallet_address(&self, address: PegWalletAddress) -> stacks_node::StacksTransaction;

    fn fulfill_peg_out(
        &self,
        op: &stacks_node::PegOutRequestOp,
    ) -> bitcoin_node::BitcoinTransaction;
}
```

Concretely, this issue is to provide an implementation of the `mint_sbtc` and `burn_sbtc` functions above.

## Recommended implementation
The current best way we know to construct stacks transactions is through [stacks.js](https://stacks.js.org/), so this task might require some JavaScript interop.

## Dependencies
- #11

Time estimate: 5 days

## Definition of done
The stacks-coordinator has a method to construct sBTC mint and burn transactions.

Let's use https://docs.hiro.so/stacks.js/feature-guides/sign-transactions

```[tasklist]
### Tasks
- [x] Connect Rust to Javascript
- [x] Make sure Stacks.js works with signing transaction.
- [ ] https://github.com/Trust-Machines/core-eng/issues/84
```

**Comment by netrome** [comment]
Note: We should not over-engineer the stacksjs integration. For the alpha release, delivery speed is key. Also, the solution must be such that the coordinator is possible to embed within the stacks-node Docker image. Sync with Jude for more detailed requirements.

**Comment by sergey-shandar** [comment]
@netrome should the `FreeWallet` functions accept `&mut self` instead of `&self` ?

**Comment by netrome** [comment]
> @netrome should the `FreeWallet` functions accept `&mut self` instead of `&self` ?

Yeah I think that's fine. The initial interface is not set in stone, but serves as a hint of what's needed from this component. Feel free to change the input types and the return types as you need. Just keep an eye on `coordinator.rs` so that it fits together with the other components, and it's good to proactively communicate any interface changes of course :).

**Comment by sergey-shandar** [comment]
Proposed structure:

```rust
pub trait StacksWallet {
    fn mint(&mut self, op: &stacks_node::PegInOp) -> stacks_node::StacksTransaction;
    fn burn(&mut self, op: &stacks_node::PegOutRequestOp) -> stacks_node::StacksTransaction;
    fn set_wallet_address(&mut self, address: PegWalletAddress) -> stacks_node::StacksTransaction;
}

pub trait BitcoinWallet {
    fn fulfill_peg_out(
        &self,
        op: &stacks_node::PegOutRequestOp,
    ) -> bitcoin_node::BitcoinTransaction;
}

pub trait PegWallet {
    type StacksWallet: StacksWallet;
    type BitcoinWallet: BitcoinWallet;
    fn stacks_mut(&mut self) -> &mut Self::StacksWallet;
    fn bitcoin_mut(&mut self) -> &mut Self::BitcoinWallet;
}
```

**Comment by diwakergupta** [comment]
> The current best way we know to construct stacks transactions is through [stacks.js](https://stacks.js.org/), so this task might require some JavaScript interop.

cc/ @janniks . FYI @sabbyanandan

**Comment by sergey-shandar** [comment]
> Nice stuff! 👌

We also need to handle IO errors.

```rust
pub trait StacksWallet {
    fn mint(&mut self, op: &stacks_node::PegInOp) -> std::io::Result<stacks_node::StacksTransaction>;
    fn burn(&mut self, op: &stacks_node::PegOutRequestOp) -> std::io::Result<stacks_node::StacksTransaction>;
    fn set_wallet_address(&mut self, address: PegWalletAddress) -> std::io::Result<stacks_node::StacksTransaction>;
}
```

**Comment by netrome** [comment]
> > Nice stuff! ok_hand
> 
> We also need to handle IO errors.
> 
> ```rust
> pub trait StacksWallet {
>     fn mint(&mut self, op: &stacks_node::PegInOp) -> std::io::Result<stacks_node::StacksTransaction>;
>     fn burn(&mut self, op: &stacks_node::PegOutRequestOp) -> std::io::Result<stacks_node::StacksTransaction>;
>     fn set_wallet_address(&mut self, address: PegWalletAddress) -> std::io::Result<stacks_node::StacksTransaction>;
> }
> ```

Cool. Is IO the only thing that can fail? Otherwise we might want to define our custom error type which contains a variant for IO errors.

**Comment by netrome** [comment]
> Cool. Is IO the only thing that can fail? Otherwise we might want to define our custom error type which contains a variant for IO errors.

Also I suppose for traits it's better to just define an associated type for the Error, and leave the specifics of the error type to the implementation. This interface is theoretically not requiring any IO.

**Comment by sergey-shandar** [comment]
> > Cool. Is IO the only thing that can fail? Otherwise we might want to define our custom error type which contains a variant for IO errors.
> 
> Also I suppose for traits it's better to just define an associated type for the Error, and leave the specifics of the error type to the implementation. This interface is theoretically not requiring any IO.

In theory, IO is the only source of errors and entropy. :-) In practice, we can introduce our error type if/when needed.

**Comment by sergey-shandar** [comment]
See also PR #76
