### ISSUE TITLE
Improve Miner debuggability

### ISSUE THREAD

**Issue by stjepangolemac** [Trust-Machines/core-eng#165]
For unknown reasons some 2.1 miners have been deadlocking and required restarts to return to normal operation.

- @donpdonp noted this might be an example of this bug https://github.com/stacks-network/stacks-blockchain/issues/3601

```[tasklist]
### Tasks

```
Igor
- Create multiple testnet miner keychains
- Create multiple mainnet miner keychains
- Setup multiple testnet miners in k8s cluster
- Setup multiple mainnet miners in k8s cluster

Stjepan
- Replenish testnet BTC: Stjepan (100 sats/byte x 300 bytes/tx = 30k sats/tx) Need to run 10 miners for 1 week
- Add metric to stacks-doctor to track Bitcoin MEV activity https://github.com/stacks-network/stacks-blockchain/discussions/3619

Mike
- Figure out how to stack using blockstack-cli. Also PR to fix cli help.
- stack-stx testnet

Low-priority:
- [ ] Expose miner's timestamp for last committed burnchain tx to use as miner health check
- [ ] Add health check to k8s so we can detect problematic miners
- [ ] Create script based on status-sh to monitor miner health of other miners

Notes:
- Matthew's testnet miner config https://github.com/zone117x/tbtc-mining
- https://www.nicehash.com

**Comment by diwakergupta** [comment]
@igorsyl @stjepangolemac shouldn't this be opened against the [stacks-blockchain](https://github.com/stacks-network/stacks-blockchain/) repo? We've encountered at least 2 live lock style issues on 2.1 testnet miner as well, so IMO this is pretty critical to escalate and fix. Do you happen to have stack trace from the deadlocked miner? Could you bring this up in today's blockchain call? Thanks! 

cc/ @jcnelson @kantai

**Comment by radicleart** [comment]
other  faucets options..
 - https://testnet-faucet.com/btc-testnet/ 
 - https://bitcoinfaucet.uo1.net/send.php 
 - https://support.chainstack.com/hc/en-us/articles/900001638963-Bitcoin-testnet-faucets

**Comment by igorsyl** [comment]
> @igorsyl @stjepangolemac shouldn't this be opened against the [stacks-blockchain](https://github.com/stacks-network/stacks-blockchain/) repo? We've encountered at least 2 live lock style issues on 2.1 testnet miner as well, so IMO this is pretty critical to escalate and fix. Do you happen to have stack trace from the deadlocked miner? Could you bring this up in today's blockchain call? Thanks!

Agreed but GitHub doesn't allow to transfer issues across Orgs.

**Comment by stjepangolemac** [comment]
Here are some thoughts on miner health / liveness checks.

A few things we mentioned in the voice chat that could be good proxies for this:

1. Recent BTC burns
2. Recent STX earnings

The problem with these is that they are (probably) external metrics that should be read elsewhere — not querying the local instance. On the other hand, if we can get this info from the node itself there is probably better data that can tell us if it's working correctly.

@igorsyl I believe you mentioned that we'd want to avoid going to external services for these kinds of checks? Can you confirm or elaborate?

After following the logic behind RPCs it seems they all refer to the `PeerNetwork` type which has a lot of data we could use.

https://github.com/stacks-network/stacks-blockchain/blob/d5738b48c66704c93b4c14bee5e8547392979729/src/net/p2p.rs#L235-L371

To be it seems we have two options:

1. Use local node data and add a `/health` RPC that can be as simple or complex as we need it
2. Run a script with every node that queries the rest of the network for BTC burns and STX earnings for that particular node

Thoughts? cc @jferrant @igorsyl

**Comment by igorsyl** [comment]
We can get this from the node itself: Recent STX earnings.

**Comment by jferrant** [comment]
Copying @kantai's Discord comment:

"When I'm trying to monitor our testnet miner or a mock miner, I typically look for log lines like
Miner: mined anchored block

which contains a bunch of useful information about the blocks its trying to mine
https://github.com/stacks-network/stacks-blockchain/blob/master/src/chainstate/stacks/miner.rs#L2650

and then I also look for these log lines:
https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/neon_node.rs#L1959-L1981
which also can indicate when something is going wrong with the miner

if the miner is at the chain tip, and none of those log lines are appearing after ~30 minutes, that indicates something is probably wrong"

Based on ^, a simple addition to that /health check could be to add two fields like so that give a probability of an issue being around based on the last time those logged lines were seen:
"
Potential Issue Probability: HIGH
Time Since Last Logged: 60 mins
"
Could also add it as an alert or something in Grafana if we already trawl the data logs.

**Comment by stjepangolemac** [comment]
Yeah that some very valuable info, and also goes hand in hand with the rest of the plan. This tool could potentially source data from all these sources:

- RPC API
- DB
- Logs

**Comment by kantai** [comment]
> Use local node data and add a /health RPC that can be as simple or complex as we need it


I'd advocate for extending the existing `monitoring` module and prometheus integration for this. In addition to being an existing endpoint, prometheus is a standard way to provide process metrics to monitoring systems.

**Comment by stjepangolemac** [comment]
@igorsyl I've updated the description to include the recent Bitcoin MEV discussion. Can you describe what we want to do a bit more?
